### PR TITLE
Fix off-by-one in range check

### LINKED ISSUE #148: runtime panics in psi
```
panic: runtime error: index out of range [2] with length 2

goroutine 180 [running]:
github.com/Comcast/gots/psi.sectionLength(...)
	github.com/Comcast/gots@v0.0.0-20201111000122-5e29012f8ad4/psi/psi.go:74
github.com/Comcast/gots/psi.SectionLength(...)
	github.com/Comcast/gots@v0.0.0-20201111000122-5e29012f8ad4/psi/psi.go:60
github.com/Comcast/gots/psi.pat.NumPrograms(0xc0024e60c4, 0xb8, 0xb8, 0x6ed1c5)
	github.com/Comcast/gots@v0.0.0-20201111000122-5e29012f8ad4/psi/pat.go:77 +0xa6
github.com/Comcast/gots/psi.pat.ProgramMap(0xc0024e60c4, 0xb8, 0xb8, 0x0)
	github.com/Comcast/gots@v0.0.0-20201111000122-5e29012f8ad4/psi/pat.go:97 +0x74
```

```
panic: runtime error: index out of range [10] with length 10

goroutine 182 [running]:
github.com/Comcast/gots/psi.(*pmt).parsePMTSection(0xc004d1a000, 0xc0012af9d4, 0xa, 0x234, 0xc004c5d1a0, 0x6f037f)
	github.com/Comcast/gots@v0.0.0-20201111000122-5e29012f8ad4/psi/pmt.go:126 +0x7d1
github.com/Comcast/gots/psi.(*pmt).parseTables(0xc004d1a000, 0xc0012af700, 0x2e0, 0x508, 0x508, 0x0)
	github.com/Comcast/gots@v0.0.0-20201111000122-5e29012f8ad4/psi/pmt.go:106 +0x10c
github.com/Comcast/gots/psi.NewPMT(0xc0012af700, 0x2e0, 0x508, 0x4, 0x0, 0x0, 0x0)
	github.com/Comcast/gots@v0.0.0-20201111000122-5e29012f8ad4/psi/pmt.go:92 +0x69
```

### PR DESCRIPTION
**Pull request by tmm1**
fixes #148:

```
panic: runtime error: index out of range [10] with length 10

goroutine 182 [running]:
github.com/Comcast/gots/psi.(*pmt).parsePMTSection(0xc004d1a000, 0xc0012af9d4, 0xa, 0x234, 0xc004c5d1a0, 0x6f037f)
	github.com/Comcast/gots@v0.0.0-20201111000122-5e29012f8ad4/psi/pmt.go:126 +0x7d1
github.com/Comcast/gots/psi.(*pmt).parseTables(0xc004d1a000, 0xc0012af700, 0x2e0, 0x508, 0x508, 0x0)
	github.com/Comcast/gots@v0.0.0-20201111000122-5e29012f8ad4/psi/pmt.go:106 +0x10c
github.com/Comcast/gots/psi.NewPMT(0xc0012af700, 0x2e0, 0x508, 0x4, 0x0, 0x0, 0x0)
	github.com/Comcast/gots@v0.0.0-20201111000122-5e29012f8ad4/psi/pmt.go:92 +0x69
```

cc @LimitlessEarth

### CODE REVIEW

**Comment by LimitlessEarth** [comment]
Looking

File: psi/pmt.go [hunk 1]
```diff
@@ -119,7 +119,7 @@ func (p *pmt) parsePMTSection(pmtBytes []byte) error {
 	var elementaryStreams []PmtElementaryStream
 	sectionLength := sectionLength(pmtBytes)
 
-	if len(pmtBytes) < programInfoLengthOffset {
```
Comment (LimitlessEarth) [inline psi/pmt.go:122]: From what I am seeing in ISO_IEC-13818, Section 2.4.4.8 the total `TS_program_map_section()` up to and including the `program_info_length` is 12 bytes. 

| field | bits |
| --- | --- |
| table_id | 8 |
| section_syntax_indicator | 1 |
| '0' | 1 |
| reserved | 2 |
| section_length | 12 |
| program_number | 16 |
| reserved | 2 |
| version_number | 5 |
| current_next_indicator | 1 |
| section_number | 8 |
|last_section_number | 8 | 
| reserved | 3 |
| PCR_PID | 13 |
| reserved | 4 |
| program_info_length | 12 |


I think this solution does work, it is essentially `len(pmtBytes) < 12` which I totally agree with

**Review by LimitlessEarth — APPROVED** [review]
